<?php

/** 
 * Implements hook_context_easy
 */
function example_ce_context_easy() {
  $contexts = array();
  
  $contexts['even_minute'] = array(
    'type' => 'condition',
    'title' => 'Is even minute',
    'description' => 'Active when the current minute is even',
    'function' => 'example_ce_check_even'
  );

  
  $contexts['odd_minute'] = array(
    'type' => 'condition',
    'title' => 'Is odd minute',
    'description' => 'Active when the current minute is odd',
    'function' => 'example_ce_check_odd'
  );
  
  
  $contexts['ppppp'] = array(
    'type' => 'reaction',
    'title' => 'ppppp',
    'description' => 'ppppp',
    'function' => 'ppppp'
  );
  
  return $contexts;
}



function example_ce_check_even() {
  print_r("executing example_ce_check_even");
  
  $minute = date("i");
  
  if ($minute % 2 == 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }

}

function example_ce_check_odd() {
  print_r("executing example_ce_check_odd");
  
  $minute = date("i");
  
  if ($minute % 2 != 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }

}

function ppppp() {
  print_r("executing ppppp");
}


